version: "3"

services:
  jarvis:
    container_name: jarvis
    image: jarvis
    build: .
    restart: always
    links:
      - "signal-gateway:signal"
      - "redis:redis"
    volumes:
        - /data/jarvis/jarvis.cfg:/etc/jarvis/jarvis.cfg
        - /data/jarvis/jarvis.db:/etc/jarvis/jarvis.db
  signal-gateway:
    container_name: signal-web-gateway
    image: signal-web-gateway
    build: ./docker/signal-web-gateway
    restart: always
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - signal-web-gateway_config:/signal/.config
      - signal-web-gateway_storage:/signal/.storage
    links:
      - "redis:redis"
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 127.0.0.1:6379:6379
volumes:
  signal-web-gateway_config:
    external: true
  signal-web-gateway_storage:
    external: true
