version: '3.6'
services:
  jarvis:
    build: .
    container_name: jarvis
    volumes:
      - /data/jarvis/jarvis.cfg:/etc/jarvis/jarvis.cfg
      - /data/jarvis/jarvis.db:/etc/jarvis/jarvis.db
    restart:
      always
