version: '3.6'
services:
  jarvis:
    image: jarvis:latest
    container_name: jarvis
    volumes:
      - /opt/appdata/jarvis/jarvis.cfg:/jarvis.cfg
      - /opt/appdata/jarvis/jarvis.db:/jarvis.db
    restart:
      always
