version: "3"

services:
  jarvis:
    container_name: jarvis
    image: jarvis
    build: .
    links:
      - "signal-gateway:signal"
      - "redis:redis"
    volumes:
        - /data/jarvis/jarvis.cfg:/etc/jarvis/jarvis.cfg
        - /data/jarvis/jarvis.db:/etc/jarvis/jarvis.db 
  signal-gateway:
    container_name: signal-web-gateway
    image: signal-web-gateway
    build: ./signal-web-gateway
    volumes:
      - signal-web-gateway_config:/signal/.config
      - signal-web-gateway_storage:/signal/.storage
    links:
      - "redis:redis"
  redis:
    container_name: redis
    image: redis:latest
volumes:
  signal-web-gateway_config:
    external: true
  signal-web-gateway_storage:
    external: true
