PUGME_URL = 'http://pugme.herokuapp.com/random'
CAT_URL = 'http://aws.random.cat/meow'
JOKE_URL = 'https://icanhazdadjoke.com/'
GREETINGS = ['hello', 'hi', 'hey', 'hola', 'bonjour']
INTRODUCTIONS = ['my name is', 'im', "i'm"]
STATEMENTS =  ['you are', 'this is', 'we are']
QUESTIONS = ['what is', 'whats', 'do you', 'how do', 'when']
VULGARITIES = ['shutup', 'stfu', 'shut up', 'fuck']
COMMANDS = ['ping', 'help', 'whoami', 'get', 'set', 'list', 'delete']
ADMIN_CMDS = ['set', 'list', 'delete']
PHONE_REGEX = "^(\+\d{1,2})?[\s.-]?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$"
